---
title: "RD24 - Data Cleaning"
author: "Benjamin Allen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(mice)
knitr::opts_chunk$set(echo = TRUE)
```

## Importing Data

```{r}
crude_data <- read_csv("../Data/training.csv")
```


## Removing Rows & Columns

```{r}
oil_data <- crude_data %>% 
  select(-OilPeakRate) %>% # Remove response temporarily to avoid data leakage
  select(-c(average_frac_fluid_per_stage, average_stage_length,
            average_proppant_per_stage)) %>% # Remove columns with >90% missing rows
  mutate(horizontal_dist_x = abs(horizontal_midpoint_x - horizontal_toe_x),
         horizontal_dist_y = abs(horizontal_midpoint_y - horizontal_toe_y),
         horizontal_dist = sqrt((horizontal_midpoint_x - horizontal_toe_x)^2 + (horizontal_midpoint_y - horizontal_toe_y)^2)) %>% # Create horizontal distance variables
  # Remove extra X and Y variables as they don't add much new info
  # Remove frac_type as it is the same for all rows and the id variables
  # Remove frac_fluid_proppant_ratio as the inverse ratio is also in the dataset
  select(-c(bh_x, bh_y, horizontal_midpoint_x, horizontal_midpoint_y, horizontal_toe_x, horizontal_toe_y,
            frac_type, pad_id, frac_fluid_to_proppant_ratio))

```


## Imputing Missing Data

Imputation is done using the MICE (Multiple Imputation by Chained Equations) approach as this is a well-proven technique for doing imputation for multiple columns.

```{r}
imputation_epoch1 <- mice(oil_data, m=5, method="rf", maxit=2, seed=24)
imputed_data <- complete(imputation_epoch1, 1)
imputed_data$ffs_frac_type <- ifelse(is.na(imputed_data$ffs_frac_type), "Unknown", imputed_data$ffs_frac_type)

# Check no more missing values
as.data.frame(sapply(imputed_data, function(y) sum(is.na(y))))

# Finally need to remove rows that are missing the response
imputed_data <- crude_data %>% 
  select(...1, `OilPeakRate`) %>% 
  inner_join(imputed_data) %>% 
  filter(!is.na(OilPeakRate)) # Remove rows where response is missing
```

## Removing Outliers

```{r}
imputed_data <- imputed_data %>% 
  # Total proppant includes a value that is about 45x larger than the rest
  filter(total_proppant < max(total_proppant)) %>% 
  # Total fluid includes a value that is almost 3x larger than the rest
  filter(total_fluid < max(total_fluid))
```

## Exporting Cleaned CSV

```{r}
write_csv(imputed_data, "../Data/cleaned_training.csv")
```

## Preprocessing

```{r}
refined_data <- imputed_data %>%
  mutate(ffs_frac_type = ifelse(ffs_frac_type == "Unknown",
                                         "Unknown - FFS", relative_well_position)) %>% 
  mutate(relative_well_position = ifelse(relative_well_position == "Unknown",
                                         "Unknown - RWP", relative_well_position)) %>% 
  mutate(batch_frac_classification = ifelse(batch_frac_classification == "Unknown",
                                         "Unknown - BFC", batch_frac_classification)) %>% 
  mutate(well_family_relationship = ifelse(well_family_relationship == "Unknown",
                                         "Unknown - WFR", well_family_relationship)) %>% 
  mutate(value = 1) %>% spread(ffs_frac_type, value,  fill = 0) %>% # One-Hot Encoding
  mutate(value = 1) %>% spread(relative_well_position, value,  fill = 0) %>% 
  mutate(value = 1) %>% spread(batch_frac_classification, value,  fill = 0) %>% 
  mutate(value = 1) %>% spread(well_family_relationship, value,  fill = 0) %>% 
  select(-...1)
```

## Exporting Preprocessed CSV

```{r}
write_csv(refined_data, "../Data/preprocessed_training.csv")
```